server:
  port: 8081

spring:
  h2.console.enabled: true
  datasource.url: jdbc:h2:mem:inventory
  data.jpa.repositories.bootstrap-mode: default
  kafka.consumer.client-id: consumer-inventory-service

spring.cloud.stream:
  kafka:
    binder:
     replication-factor: 1
  function:
    definition: inventoryProcessor
  bindings:
    inventoryProcessor-in-0:
      destination: order-event
    inventoryProcessor-out-0:
      destination: inventory-event